# This file was generated by GoReleaser. DO NOT EDIT.
cask "beans" do
  name "beans"
  desc "Agentic-first issue tracker"
  homepage "https://github.com/hmans/beans"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beans"

  on_macos do
    on_intel do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Darwin_x86_64.tar.gz"
      sha256 "6f4e6b94b75cd4cf39992daef5070274ad2b5f2aa1707f2f023551c942a33ae7"
    end
    on_arm do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Darwin_arm64.tar.gz"
      sha256 "d61f27ad61f962f8df81f6e78b236175d43f6d90458fd656bc98b11dc19ead77"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Linux_x86_64.tar.gz"
      sha256 "5dac19172a15cbbd716c34fc41f226281afb934b724ef314f73b905baf5c9dcb"
    end
    on_arm do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Linux_arm64.tar.gz"
      sha256 "517e29d007995fcdfe169fdd3997cf9d51099bbdab7767422e53a4f058ceb8fd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans"]
    end
  end

  # No zap stanza required
end
