# This file was generated by GoReleaser. DO NOT EDIT.
cask "beans" do
  name "beans"
  desc "Agentic-first issue tracker"
  homepage "https://github.com/hmans/beans"
  version "0.1.29"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beans"

  on_macos do
    on_intel do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Darwin_x86_64.tar.gz"
      sha256 "76d0185c7db29d15e6a44e8c97fc8e332ad79912215ea051519dba4187c00695"
    end
    on_arm do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Darwin_arm64.tar.gz"
      sha256 "3c8dd00564ff139900d1135454741702c7a8e66cd33f4f832c266154abd54399"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Linux_x86_64.tar.gz"
      sha256 "fe2706bf363fdfb8f42f698da401c329a54f45465c386ab6ebabe626bc0a34a6"
    end
    on_arm do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Linux_arm64.tar.gz"
      sha256 "3b2515a345242c23e19d9f9d8c3bb09644cc07ec583d0dcb6281b1d03c17c74d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans"]
    end
  end

  # No zap stanza required
end
