# This file was generated by GoReleaser. DO NOT EDIT.
cask "beans" do
  name "beans"
  desc "Agentic-first issue tracker"
  homepage "https://github.com/hmans/beans"
  version "0.1.24"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beans"

  on_macos do
    on_intel do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Darwin_x86_64.tar.gz"
      sha256 "0b885c305b329fb482afbb77c64b2b9857c59e842cdf816a89a3abcc16127095"
    end
    on_arm do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Darwin_arm64.tar.gz"
      sha256 "bad92491716043a2e3515a02cfb2135f807636c45179f80325ca06d7d5a6d044"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Linux_x86_64.tar.gz"
      sha256 "2cfb32bad30b307f05a27caf2bae97be07daab02af4aba3182b86fc391b88062"
    end
    on_arm do
      url "https://github.com/hmans/beans/releases/download/v#{version}/beans_Linux_arm64.tar.gz"
      sha256 "65cd73b6940f1e73331e5114b9d0ff72d86649900ff3b15aac720ff93ba5235f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/beans"]
    end
  end

  # No zap stanza required
end
